export default {
    updateProjectname({commit},projectname){
        commit('updateProjectname',projectname);
    },
    updateApptype({commit},apptype){
        commit('updateApptype',apptype);
    },
    updateProjects({commit},projects){
        commit('updateProjects',projects);
    },
    updateMembers({commit},members){
        commit('updateMembers',members);
    },
    resetState({commit}){
        commit('resetState');
    },
    updateStakeholder({commit},stakeholder){
        commit('updateStakeholder',stakeholder)
    },
    updateFairnesscard({commit},fairnesscard){
        commit('updateFairnesscard',fairnesscard)
    },
    updateFairnesscards({commit},fairnesscards){
        commit('updateFairnesscards',fairnesscards)
    },
    updateGoright({commit},goright){
        commit('updateGoright',goright)
    },
    updateGowrong({commit},gowrong){
        commit('updateGowrong',gowrong)
    }
}